[workspace]
members = [
  "crates/clash-verge-core",
  "src-tui",
]
default-members = ["src-tui"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
rust-version = "1.95"

[workspace.dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
chrono = "0.4.45"
clap = { version = "4.6", features = ["derive"] }
color-eyre = "0.6"
crossterm = { version = "0.29", features = ["event-stream"] }
dirs = "5"
log = "0.4.32"
parking_lot = { version = "0.12.5", features = ["hardware-lock-elision"] }
ratatui = { version = "0.30", features = ["crossterm"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_yaml_ng = "0.10.0"
smartstring = { version = "1.0.1", features = ["serde"] }
thiserror = "2.0"
tokio = { version = "1.52.3", features = [
  "rt-multi-thread",
  "macros",
  "time",
  "sync",
  "signal",
  "fs",
] }
tracing = "0.1"

[profile.release]
panic = "unwind"
codegen-units = 1
lto = "thin"
opt-level = 3
strip = "symbols"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
dbg_macro = "deny"
todo = "warn"
unimplemented = "deny"
